### PR TITLE
Feature/unittest

### PR DESCRIPTION
**Pull request by elenaferr0**

### CODE REVIEW

**Comment by elenaferr0** [comment]
# ☂️ Python Coverage
> current status: ❌
## Overall Coverage
| Lines | Covered | Coverage | Threshold | Status |
| :---: | :-----: | :------: | :-------: | :----: |
|  467  |   244   |    52%   |    80%    |   🔴   |
## New Files
| File                      | Coverage | Status |
| :------------------------ | :------: | :----: |
| simulator/src/__init__.py |   100%   |   🟢   |
| **TOTAL**                 | **100%** |   🟢   |
## Modified Files
| File                                                  | Coverage | Status |
| :---------------------------------------------------- | :------: | :----: |
| simulator/src/models/config/env_config.py             |    96%   |   🟢   |
| simulator/src/models/config/simulator_factory.py      |    89%   |   🟢   |
| simulator/src/models/raw_data/raw_data.py             |    83%   |   🟢   |
| simulator/src/models/raw_data/temperature_raw_data.py |    84%   |   🟢   |
| simulator/src/simulators/recycling_point_simulator.py |    26%   |   🟢   |
| simulator/src/simulators/simulator.py                 |    90%   |   🟢   |
| simulator/src/simulators/temperature_simulator.py     |    97%   |   🟢   |
| simulator/src/simulators/traffic_simulator.py         |    52%   |   🟢   |
| **TOTAL**                                             |  **77%** |   🟢   |


> **updated for commit: `44213ac` by [action](https://github.com/marketplace/actions/python-coverage)🐍**

**Comment by elenaferr0** [comment]
# ☂️ Python Coverage
> current status: ❌
## Overall Coverage
| Lines | Covered | Coverage | Threshold | Status |
| :---: | :-----: | :------: | :-------: | :----: |
|  563  |   420   |    75%   |    80%    |   🔴   |
## New Files
| File                      | Coverage | Status |
| :------------------------ | :------: | :----: |
| simulator/src/__init__.py |   100%   |   🟢   |
| **TOTAL**                 | **100%** |   🟢   |
## Modified Files
| File                                                  | Coverage | Status |
| :---------------------------------------------------- | :------: | :----: |
| simulator/src/models/config/env_config.py             |    96%   |   🟢   |
| simulator/src/models/config/simulator_factory.py      |    82%   |   🟢   |
| simulator/src/models/raw_data/raw_data.py             |    82%   |   🟢   |
| simulator/src/models/raw_data/temperature_raw_data.py |    89%   |   🟢   |
| simulator/src/serializers/avro_serializer.py          |    48%   |   🟢   |
| simulator/src/simulators/recycling_point_simulator.py |    90%   |   🟢   |
| simulator/src/simulators/simulator.py                 |    90%   |   🟢   |
| simulator/src/simulators/temperature_simulator.py     |    97%   |   🟢   |
| simulator/src/simulators/traffic_simulator.py         |    97%   |   🟢   |
| **TOTAL**                                             |  **86%** |   🟢   |


> **updated for commit: `ee0fe83` by [action](https://github.com/marketplace/actions/python-coverage)🐍**

**Comment by elenaferr0** [comment]
# ☂️ Python Coverage
> current status: ❌
## Overall Coverage
| Lines | Covered | Coverage | Threshold | Status |
| :---: | :-----: | :------: | :-------: | :----: |
|  563  |   449   |    80%   |    80%    |   🔴   |
## New Files
| File                      | Coverage | Status |
| :------------------------ | :------: | :----: |
| simulator/src/__init__.py |   100%   |   🟢   |
| **TOTAL**                 | **100%** |   🟢   |
## Modified Files
| File                                                  | Coverage | Status |
| :---------------------------------------------------- | :------: | :----: |
| simulator/src/models/config/env_config.py             |    96%   |   🟢   |
| simulator/src/models/config/simulator_factory.py      |    82%   |   🟢   |
| simulator/src/models/raw_data/air_quality_raw_data.py |    78%   |   🟢   |
| simulator/src/models/raw_data/raw_data.py             |    82%   |   🟢   |
| simulator/src/models/raw_data/temperature_raw_data.py |    89%   |   🟢   |
| simulator/src/serializers/avro_serializer.py          |    48%   |   🟢   |
| simulator/src/simulators/air_quality_simulator.py     |   100%   |   🟢   |
| simulator/src/simulators/recycling_point_simulator.py |    90%   |   🟢   |
| simulator/src/simulators/simulator.py                 |    90%   |   🟢   |
| simulator/src/simulators/temperature_simulator.py     |    97%   |   🟢   |
| simulator/src/simulators/traffic_simulator.py         |    97%   |   🟢   |
| **TOTAL**                                             |  **86%** |   🟢   |


> **updated for commit: `62ce058` by [action](https://github.com/marketplace/actions/python-coverage)🐍**

**Comment by elenaferr0** [comment]
# ☂️ Python Coverage
> current status: ❌
## Overall Coverage
| Lines | Covered | Coverage | Threshold | Status |
| :---: | :-----: | :------: | :-------: | :----: |
|  567  |   453   |    80%   |    80%    |   🔴   |
## New Files
| File                      | Coverage | Status |
| :------------------------ | :------: | :----: |
| simulator/src/__init__.py |   100%   |   🟢   |
| **TOTAL**                 | **100%** |   🟢   |
## Modified Files
| File                                                  | Coverage | Status |
| :---------------------------------------------------- | :------: | :----: |
| simulator/src/models/config/env_config.py             |    96%   |   🟢   |
| simulator/src/models/config/simulator_factory.py      |    82%   |   🟢   |
| simulator/src/models/raw_data/air_quality_raw_data.py |    84%   |   🟢   |
| simulator/src/models/raw_data/raw_data.py             |    82%   |   🟢   |
| simulator/src/models/raw_data/temperature_raw_data.py |    89%   |   🟢   |
| simulator/src/serializers/avro_serializer.py          |    48%   |   🟢   |
| simulator/src/simulators/air_quality_simulator.py     |    98%   |   🟢   |
| simulator/src/simulators/recycling_point_simulator.py |    90%   |   🟢   |
| simulator/src/simulators/simulator.py                 |    90%   |   🟢   |
| simulator/src/simulators/temperature_simulator.py     |    97%   |   🟢   |
| simulator/src/simulators/traffic_simulator.py         |    97%   |   🟢   |
| **TOTAL**                                             |  **87%** |   🟢   |


> **updated for commit: `d7bc67f` by [action](https://github.com/marketplace/actions/python-coverage)🐍**

**Comment by elenaferr0** [comment]
# ☂️ Python Coverage
> current status: ✅
## Overall Coverage
| Lines | Covered | Coverage | Threshold | Status |
| :---: | :-----: | :------: | :-------: | :----: |
|  515  |   441   |    86%   |    80%    |   🟢   |
## New Files
| File                      | Coverage | Status |
| :------------------------ | :------: | :----: |
| simulator/src/__init__.py |   100%   |   🟢   |
| **TOTAL**                 | **100%** |   🟢   |
## Modified Files
| File                                                  | Coverage | Status |
| :---------------------------------------------------- | :------: | :----: |
| simulator/src/models/config/env_config.py             |    96%   |   🟢   |
| simulator/src/models/config/simulator_factory.py      |    82%   |   🟢   |
| simulator/src/models/raw_data/air_quality_raw_data.py |    84%   |   🟢   |
| simulator/src/models/raw_data/raw_data.py             |    80%   |   🟢   |
| simulator/src/models/raw_data/temperature_raw_data.py |    89%   |   🟢   |
| simulator/src/producers/stdout_producer.py            |    91%   |   🟢   |
| simulator/src/runner.py                               |    0%    |   🟢   |
| simulator/src/serializers/avro_serializer.py          |    96%   |   🟢   |
| simulator/src/serializers/json_serializer.py          |   100%   |   🟢   |
| simulator/src/serializers/serializer_strategy.py      |    89%   |   🟢   |
| simulator/src/simulators/air_quality_simulator.py     |    98%   |   🟢   |
| simulator/src/simulators/recycling_point_simulator.py |    90%   |   🟢   |
| simulator/src/simulators/simulator.py                 |    90%   |   🟢   |
| simulator/src/simulators/temperature_simulator.py     |    97%   |   🟢   |
| simulator/src/simulators/traffic_simulator.py         |    97%   |   🟢   |
| **TOTAL**                                             |  **85%** |   🟢   |


> **updated for commit: `ee2cfc9` by [action](https://github.com/marketplace/actions/python-coverage)🐍**

**Review by abenetazzo — APPROVED** [review]

**Pull request merged**
